Revert "Fixed warnings on the generated Paths module."
This reverts commit df6fe40cef1414b77dab92a6f6b8fb2fdbb9ccd9.

It broke the build on Windows, e.g.:

utils\hsc2hs\dist\build\autogen\Paths_hsc2hs.hs:45:34:
    Not in scope: `fromIntegral'