bootstrap.sh: bump 1.24's minimum Cabal to 1.24.1
otherwise a local Cabal 1.24.0.0 will cause build failure

```
  Distribution/Client/Setup.hs:76:40: error:
      Module
      ‘Distribution.Simple.Configure’
      does not export
      ‘computeEffectiveProfiling’
```

due to haskell/cabal@fbfc811.