Fix lower bound on `Cabal`
`cabal` needs at least Cabal-1.24.1 otherwise it fails to compile with

    Distribution/Client/Setup.hs:76:40: error:
        Module ‘Distribution.Simple.Configure’
        does not export ‘computeEffectiveProfiling’

I've already fixed this on hackage via

  http://hackage.haskell.org/package/cabal-install-1.24.0.1/revisions/  

so there's no need to upload a new release to Hackage just for this.