Use package groups (backport #9565) (#10006)
* Import packages from project-cabal/pkgs

- Move constraints to project-cabal/constraints.config
- Remove duplicate package groups
- Groups coverage, doctest and validate are the same as the default group
- Remove duplicate validate-libonly package group
- Both validate and validate-libonly are the same
- Move Cabal & Cabal-syntax to pkgs/cabal.config
- Add install package group
- Add benchmarks package group
- Add tests package group
- Both default and libonly groups were the same set of packages that I renamed to tests
- Put install group before tests and benchmarks
- Don't repeat packages
- Add TODO and REVIEW comments on allow-newer exceptions
- Move latest.ghc configuration
- Put program-options first & separate imports
- Remove optional-packages
- Don't reiterate default value for tests and benchmarks
- Don't reiterate default value for optimization
- Add ghc-options.config
- Rename to ghc-latest.config
- Use -Werror in ghc-options.config
- Don't include ghc-options.config for doctest project
- Add project-config/pkgs.config
- Add project-config/pkgs.config importing all package groups
- Move Cabal-described to the cabal package group
- Remove cabal.project.buildinfo
- Have cabal.project.doctest import cabal.project
- Split integration tests into their own package group.
- Add back trailing newlines at EOF in projects
- Integration-tests.config needed for libonly
- Add a README for projects.

(cherry picked from commit 0876e187ac2682327448866e22eadafe4763a8a3)

# Conflicts:
#	cabal.project.release

* Build all local packages with -Werror

- Satisfy -Wmissing-signatures in test-runtime-deps
- Satisfy -Wx-partial in HackageBenchmark
- Satisfy -Wunused-imports in QuickCheck.Instances.Cabal
- Use partial pattern for filtering in list comprehension
- Don't error on deprecated import

(cherry picked from commit 8453ee0bbf9936204f5e8b7aa145bcad8caeb1ec)

* Add an intercepting cabal-testsuite/cabal.project

- Reduce duplication in test flag setup
- Avoid "New config" picking cabal's own project

Before this change, this was the test failure:

Unit Tests
  UnitTests.Distribution.Client.Configure
    Configure tests
      New config:                     FAIL
        Exception: project-cabal/pkgs/cabal.config: withBinaryFile: does not exist (No such file or directory)
        Use -p '/New config/' to rerun this test only.
      Replacement + new config:       OK
      Old + new config:               OK
      Old + new config, no appending: OK
      Old + new config, backup check: OK
      Local program options:          OK

1 out of 6 tests failed (0.02s)

(cherry picked from commit d33627598ad027d764c9f2015ac29004aa024657)

* Remove dangling doctest TODO left over from #9572

(cherry picked from commit 619befd0b63ce5dff2a620302f3b75c3de6e74c4)

* Remove allow-newer exception for cryptohash-sha256:base

(cherry picked from commit ed5d40444bcce7473e9b860a60c6c02d6a212399)

* Remove projects; weeder, doctest & libonly

* Remove cabal.project.libonly

It was only referenced once in a stale Makefile comment about doctests.

* Remove weeder

- remove weeder's configuration
- remove its recipe from Makefile
- remove its project

* Delete cabal.project.doctest

- Adding --ghc-options="-Wwarn" is sufficient to avoid the numerous <interactive> failures seen otherwise
- write-ghc-environment-files has a default of never

(cherry picked from commit 72be26bd8e8e6071bf5f9cbfb572f7d3e374a0fb)

* Update cabal.project.release

---------

Co-authored-by: Phil de Joux <philderbeast@gmail.com>
Co-authored-by: Hécate <Kleidukos@users.noreply.github.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>