Fix #7705: only write default configuration if no --config-file
New behavior, e.g.:
```
$ cabal --config-file=ABSENT info happy

Config file path source is commandline option.
Error: cabal: Config file not found: ABSENT
(Config files can be created via the cabal-command 'user-config init'.)

$ CABAL_CONFIG=missing.file cabal info frown

Config file path source is environment variable CABAL_CONFIG.
Error: cabal: Config file not found: missing.file
(Config files can be created via the cabal-command 'user-config init'.)
```