Fix `--keep-temp-files` given to Cabal lib versions that don't have it.
`Cabal < 3.13` did not support this flag
(it did for `... haddock` but not `... repl`).
So `Setup.hs` compiled with such older versions rejects it.

This causes errors for users of `haskell-language-server` if
they have a custom `Setup.hs` depending on `Cabal < 3.13`,
because it makes `hie-bios` pass the nonexistent flag,
causing error:

    unrecognized 'repl' option `--keep-temp-files'
    Error: [Cabal-7125]
    repl failed for my-package-0.1.0.0.

`filterCommonFlags` already removes the flag for `lib:Cabal < 3.13`.